In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("customer_shopping_behavior.csv")

In [8]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [5]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [7]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [13]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [14]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [17]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'})

In [18]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [19]:
#Create a column age group
labels = ['Young Adult','Adult','Middle-Aged','senior']
df['age_group'] = pd.qcut(df['age'],q=4, labels = labels)

In [20]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-Aged
1   19  Young Adult
2   50  Middle-Aged
3   21  Young Adult
4   45  Middle-Aged
5   46  Middle-Aged
6   63       senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-Aged

In [ ]:
# Create column purchase_frequency_days
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [32]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                    365.0               Annually
5                      7.0                 Weekly
6                     90.0              Quarterly
7                      7.0                 Weekly
8                    365.0               Annually
9                     90.0              Quarterly

In [35]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [36]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [37]:
df = df.drop('promo_code_used',axis=1)

In [38]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'Purchase_frequency_days',
       'purchase_frequency_days'],
      dtype='object')

In [51]:
df= df.drop('Purchase_frequency_days',axis=1)

In [39]:
pip install pymysql sqlalchemy

Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
     ---------------------------------------- 0.0/45.7 kB ? eta -:--:--
     ---------------------------------------- 45.7/45.7 kB 2.2 MB/s eta 0:00:00
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.51-cp310-cp310-win_amd64.whl (2.1 MB)
     ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
     - -------------------------------------- 0.1/2.1 MB 2.2 MB/s eta 0:00:01
     --- ------------------------------------ 0.2/2.1 MB 2.5 MB/s eta 0:00:01
     ------ --------------------------------- 0.3/2.1 MB 2.5 MB/s eta 0:00:01
     ------ --------------------------------- 0.3/2.1 MB 2.5 MB/s eta 0:00:01
     ------ --------------------------------- 0.4/2.1 MB 1.9 MB/s eta 0:00:01
     ------ --------------------------------- 0.4/2.1 MB 1.9 MB/s eta 0:00:01
     ------ --------------------------------- 0.4/2.1 MB 1.9 MB/s eta 0:00:01
     ------- -------------------------------- 0.4/2.1 MB 1.2 MB/s eta 0:00:02
     ------- -------------------------------- 0.4/2.1 MB 1.2 MB/s eta 0:00:02
     ------- -------------------------------- 0.4/2.1 MB 1.2 MB/s eta 0:00:02
     ------- -------------------------------- 0.4/2.1 MB 1.2 MB/s eta 0:00:02
     ------- -------------------------------- 0.4/2.1 MB 1.2 MB/s eta 0:00:02
     ------- -------------------------------- 0.4/2.1 MB 1.2 MB/s eta 0:00:02
     ------- -------------------------------- 0.4/2.1 MB 1.2 MB/s eta 0:00:02
     ------- -------------------------------- 0.4/2.1 MB 1.2 MB/s eta 0:00:02
     ------- -------------------------------- 0.4/2.1 MB 1.2 MB/s eta 0:00:02
     ------- -------------------------------- 0.4/2.1 MB 1.2 MB/s eta 0:00:02
     ------- -------------------------------- 0.4/2.1 MB 1.2 MB/s eta 0:00:02
     ------- -------------------------------- 0.4/2.1 MB 1.2 MB/s eta 0:00:02
     ------- -------------------------------- 0.4/2.1 MB 1.2 MB/s eta 0:00:02
     ------- -------------------------------- 0.4/2.1 MB 1.2 MB/s eta 0:00:02
     ------- -------------------------------- 0.4/2.1 MB 1.2 MB/s eta 0:00:02
     ------- -------------------------------- 0.4/2.1 MB 1.2 MB/s eta 0:00:02
     ------- -------------------------------- 0.4/2.1 MB 1.2 MB/s eta 0:00:02
     ------- -------------------------------- 0.4/2.1 MB 1.2 MB/s eta 0:00:02
     ------- -------------------------------- 0.4/2.1 MB 345.2 kB/s eta 0:00:06
     ------- -------------------------------- 0.4/2.1 MB 345.2 kB/s eta 0:00:06
     ------- -------------------------------- 0.4/2.1 MB 345.2 kB/s eta 0:00:06
     ------- -------------------------------- 0.4/2.1 MB 345.2 kB/s eta 0:00:06
     ------- -------------------------------- 0.4/2.1 MB 345.2 kB/s eta 0:00:06
     ------- -------------------------------- 0.4/2.1 MB 345.2 kB/s eta 0:00:06
     ------- -------------------------------- 0.4/2.1 MB 281.9 kB/s eta 0:00:07
     ------- -------------------------------- 0.4/2.1 MB 281.9 kB/s eta 0:00:07
     -------- ------------------------------- 0.4/2.1 MB 280.7 kB/s eta 0:00:07
     -------- ------------------------------- 0.5/2.1 MB 292.0 kB/s eta 0:00:06
     --------- ------------------------------ 0.5/2.1 MB 305.3 kB/s eta 0:00:06
     ---------- ----------------------------- 0.6/2.1 MB 324.6 kB/s eta 0:00:05
     ---------- ----------------------------- 0.6/2.1 MB 336.7 kB/s eta 0:00:05
     ------------ --------------------------- 0.6/2.1 MB 365.9 kB/s eta 0:00:05
     -------------- ------------------------- 0.8/2.1 MB 421.7 kB/s eta 0:00:04
     --------------- ------------------------ 0.8/2.1 MB 455.4 kB/s eta 0:00:03
     ---------------- ----------------------- 0.9/2.1 MB 473.5 kB/s eta 0:00:03
     ---------------- ----------------------- 0.9/2.1 MB 468.8 kB/s eta 0:00:03
     ------------------ --------------------- 1.0/2.1 MB 484.9 kB/s eta 0:00:03
     ------------------- -------------------- 1.0/2.1 MB 502.9 kB/s eta 0:00:03
     ------------------- -------------------- 1.0/2.1 MB 502.9 kB/s eta 0:00:03
     -------------------- ------------------- 1.1/2.1 MB 512.5 kB/s eta 0:00:03
     ---------------------- ----------------- 1.2/2.1 MB 559.6 kB/s eta 0:00:02
     ------------------------ --------------- 1.3/2.1 MB 595.0 kB/s eta 0:00:02
     --------------------------- ------------ 1.5/2.1 MB 646.0 kB/s eta 0:00:02
     ---------------------------- ----------- 1.5/2.1 MB 668.6 kB/s eta 0:00:01
     ----------------------------- ---------- 1.6/2.1 MB 686.5 kB/s eta 0:00:01
     ------------------------------- -------- 1.7/2.1 MB 720.3 kB/s eta 0:00:01
     ------------------------------- -------- 1.7/2.1 MB 720.3 kB/s eta 0:00:01
     ------------------------------- -------- 1.7/2.1 MB 720.3 kB/s eta 0:00:01
     ------------------------------- -------- 1.7/2.1 MB 720.3 kB/s eta 0:00:01
     ---------------------------------- ----- 1.9/2.1 MB 727.7 kB/s eta 0:00:01
     ------------------------------------ --- 1.9/2.1 MB 746.1 kB/s eta 0:00:01
     ------------------------------------- -- 2.0/2.1 MB 772.9 kB/s eta 0:00:01
     ---------------------------------------  2.1/2.1 MB 801.6 kB/s eta 0:00:01
     ---------------------------------------- 2.1/2.1 MB 794.2 kB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\farooq\appdata\roaming\python\python310\site-packages (from sqlalchemy) (4.15.0)
Collecting greenlet>=1
  Downloading greenlet-3.5.4-cp310-cp310-win_amd64.whl (246 kB)
     ---------------------------------------- 0.0/246.0 kB ? eta -:--:--
     ----------------- -------------------- 112.6/246.0 kB 2.2 MB/s eta 0:00:01
     -------------------------------------  245.8/246.0 kB 2.5 MB/s eta 0:00:01
     -------------------------------------- 246.0/246.0 kB 2.5 MB/s eta 0:00:00
Installing collected packages: pymysql, greenlet, sqlalchemy
Successfully installed greenlet-3.5.4 pymysql-1.2.0 sqlalchemy-2.0.51
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [41]:
from sqlalchemy import create_engine

In [55]:
#step 1 : Connect to mysql
username = "root"
password = "12345678"
host = "127.0.0.1"
port = "3306"
database = "Customer_behavior"
engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)
#step 2: load Dataframe into Mysql
table_name ="customer"
df.to_sql(name=table_name, con=engine, if_exists="replace", index=False)
print(f"Data Successfully loaded into table '{table_name}' in database '{database}'.")

Data Successfully loaded into table 'customer' in database 'Customer_behavior'.